# Generated by Django 2.2 on 2019-12-23 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20191222_2319'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecretSanta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('santa', models.CharField(max_length=200)),
                ('player', models.CharField(max_length=200)),
                ('text', models.TextField(max_length=5000)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='lettermodel',
            name='letter',
            field=models.TextField(max_length=5000),
        ),
    ]
