# Generated by Django 2.2 on 2019-12-23 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20191223_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secretsanta',
            name='player',
            field=models.EmailField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='secretsanta',
            name='santa',
            field=models.EmailField(max_length=200, unique=True),
        ),
    ]
